version: '3'  # Hoặc phiên bản 3.x mới nhất

services:
  xweb-seller:
    build:
      context: .
    image: xweb-seller
    container_name: xweb-seller
    env_file:
      - /opt/global/.env.xweb_seller
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M  # Giới hạn bộ nhớ tương tự như mem_limit
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
      - "/usr/src/app/.next"
    networks:
      - ommanisoft

networks:
  ommanisoft:
    external: true
